# Generated by Django 4.1.7 on 2026-04-13 07:53

from django.db import migrations, models
import django.db.models.deletion
import octofit_tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(default=octofit_tracker.models.generate_objectid, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.CharField(default=octofit_tracker.models.generate_objectid, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=octofit_tracker.models.generate_objectid, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='octofit_tracker.team')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.CharField(default=octofit_tracker.models.generate_objectid, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octofit_tracker.team')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(default=octofit_tracker.models.generate_objectid, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octofit_tracker.user')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octofit_tracker.workout')),
            ],
        ),
    ]
